/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.BorderLayout;

/**
 *
 * @author mateo
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form PLogin
     */
    public frmMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        POpciones op =new POpciones();
        PLogin lg = new PLogin();
        lg.setSize(1000, 720);
        lg.setLocation(0, 0);
        
        PanelPrincipal.removeAll();
        PanelPrincipal.add(lg, BorderLayout.CENTER);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();
        
        jMenuMe.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenuMe = new javax.swing.JMenu();
        jMenuHome = new javax.swing.JMenuItem();
        jMenuItemProv = new javax.swing.JMenuItem();
        jMenuItemCiu = new javax.swing.JMenuItem();
        jMenuItemUser = new javax.swing.JMenuItem();
        jMenuItemCSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        PanelPrincipal.setPreferredSize(new java.awt.Dimension(1000, 720));

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        jMenuBar2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jMenuBar2PropertyChange(evt);
            }
        });

        jMenuMe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zIMG/menu25.png"))); // NOI18N
        jMenuMe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMeActionPerformed(evt);
            }
        });

        jMenuHome.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jMenuHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zIMG/home-outline.png"))); // NOI18N
        jMenuHome.setText("Inicio");
        jMenuMe.add(jMenuHome);

        jMenuItemProv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zIMG/icons8-mapa-del-tesoro-24.png"))); // NOI18N
        jMenuItemProv.setText("Provincias");
        jMenuItemProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProvActionPerformed(evt);
            }
        });
        jMenuMe.add(jMenuItemProv);

        jMenuItemCiu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zIMG/icons8-edificios-de-la-ciudad-24.png"))); // NOI18N
        jMenuItemCiu.setText("Ciudades");
        jMenuMe.add(jMenuItemCiu);

        jMenuItemUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zIMG/account-multiple.png"))); // NOI18N
        jMenuItemUser.setText("Usuarios");
        jMenuItemUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUserActionPerformed(evt);
            }
        });
        jMenuMe.add(jMenuItemUser);

        jMenuItemCSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zIMG/icons8-salida-24.png"))); // NOI18N
        jMenuItemCSesion.setText("Cerrar sesión");
        jMenuMe.add(jMenuItemCSesion);

        jMenuBar2.add(jMenuMe);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemUserActionPerformed

    private void jMenuMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuMeActionPerformed

    private void jMenuBar2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jMenuBar2PropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuBar2PropertyChange

    private void jMenuItemProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemProvActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel PanelPrincipal;
    public javax.swing.JMenuBar jMenuBar2;
    public javax.swing.JMenuItem jMenuHome;
    public javax.swing.JMenuItem jMenuItemCSesion;
    public javax.swing.JMenuItem jMenuItemCiu;
    public javax.swing.JMenuItem jMenuItemProv;
    public javax.swing.JMenuItem jMenuItemUser;
    public javax.swing.JMenu jMenuMe;
    // End of variables declaration//GEN-END:variables
}
