/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author mateo
 */
public class PanelLogin extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public PanelLogin() {
        initComponents();
    }
    private boolean cambio=false;

    public boolean isCambio() {
        return cambio;
    }

    public void setCambio(boolean cambio) {
        this.cambio = cambio;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonLogin = new javax.swing.JButton();
        jTextFieldNom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelMError = new javax.swing.JLabel();

        setBackground(new java.awt.Color(33, 33, 33));
        setPreferredSize(new java.awt.Dimension(1000, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Iniciar Sesión");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 74, 287, 57));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contraseña:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 306, 213, 42));

        jButtonLogin.setBackground(new java.awt.Color(0, 0, 0));
        jButtonLogin.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogin.setText("                  Login");
        jButtonLogin.setBorder(null);
        jButtonLogin.setBorderPainted(false);
        jButtonLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonLogin.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButtonLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 453, 287, 63));

        jTextFieldNom.setBackground(new java.awt.Color(33, 33, 33));
        jTextFieldNom.setText("Ingrese su nombre de usuario");
        jTextFieldNom.setBorder(null);
        jTextFieldNom.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextFieldNom.setOpaque(true);
        jTextFieldNom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldNomMousePressed(evt);
            }
        });
        jTextFieldNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNomKeyPressed(evt);
            }
        });
        add(jTextFieldNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 250, 435, -1));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingrese su usuario y contraseña");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 137, 244, -1));

        jPasswordField1.setBackground(new java.awt.Color(33, 33, 33));
        jPasswordField1.setText("               ");
        jPasswordField1.setBorder(null);
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPasswordField1MousePressed(evt);
            }
        });
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 354, 435, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuario:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 190, 213, 42));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 272, 435, 22));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 376, 435, 28));

        jLabelMError.setForeground(new java.awt.Color(255, 0, 51));
        jLabelMError.setText("*Usuario o contraseña incorrectos*");
        add(jLabelMError, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 320, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jTextFieldNomMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNomMousePressed
        // TODO add your handling code here:
        if (jTextFieldNom.getText().equals("Ingrese su nombre de usuario")) {
            jTextFieldNom.setText("");
        }
    }//GEN-LAST:event_jTextFieldNomMousePressed

    private void jPasswordField1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MousePressed
        // TODO add your handling code here:
        if (jPasswordField1.getText().equals("               ")) {
            jPasswordField1.setText("");
        }
    }//GEN-LAST:event_jPasswordField1MousePressed

    private void jTextFieldNomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomKeyPressed
        // TODO add your handling code here:
        this.cambio=true;
    }//GEN-LAST:event_jTextFieldNomKeyPressed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabelMError;
    public javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTextField jTextFieldNom;
    // End of variables declaration//GEN-END:variables
}
