/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;


import java.awt.Color;
import javax.swing.UIManager;

/**
 *
 * @author mateo
 */
public class PCompraV extends javax.swing.JPanel {

    /**
     * Creates new form PSale
     */
    public PCompraV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelProd = new javax.swing.JLabel();
        jLabelCant = new javax.swing.JLabel();
        jButtonAddCV = new javax.swing.JButton();
        jLabelErrorCant = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonVenta = new javax.swing.JButton();
        jButtonCompra = new javax.swing.JButton();
        jButtonSelectCV = new javax.swing.JButton();
        jComboBoxSelectPC = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabelProvClient = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jLabelErroPvCl = new javax.swing.JLabel();
        jLabelErrorFecha = new javax.swing.JLabel();
        jComboBoxProducto = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jTextFieldPrecio = new javax.swing.JTextField();
        jLabelErrorPrecio = new javax.swing.JLabel();
        jLabelprecio = new javax.swing.JLabel();
        jButtonQR = new javax.swing.JButton();
        jSpinnerInv = new javax.swing.JSpinner();
        jLabelTotal = new javax.swing.JLabel();
        jLabel$ = new javax.swing.JLabel();
        jLabelQr = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelProd.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabelProd.setText("Producto:");
        add(jLabelProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 280, 262, 39));

        jLabelCant.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabelCant.setText("Cantidad:");
        add(jLabelCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 466, 268, 33));

        jButtonAddCV.setBackground(new java.awt.Color(0, 0, 0));
        jButtonAddCV.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jButtonAddCV.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAddCV.setText("Agregar");
        jButtonAddCV.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        jButtonAddCV.setBorderPainted(false);
        jButtonAddCV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAddCV.setHideActionText(true);
        jButtonAddCV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAddCV.setIconTextGap(10);
        jButtonAddCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCVActionPerformed(evt);
            }
        });
        add(jButtonAddCV, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 581, 199, 63));

        jLabelErrorCant.setForeground(new java.awt.Color(255, 0, 51));
        jLabelErrorCant.setText("*Ha exedido el stock del producto *");
        add(jLabelErrorCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 505, 240, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(308, 720));

        jButtonVenta.setBackground(new java.awt.Color(0, 0, 0));
        jButtonVenta.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jButtonVenta.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zIMG/icons8-venta-24.png"))); // NOI18N
        jButtonVenta.setText("Ventas");
        jButtonVenta.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        jButtonVenta.setBorderPainted(false);
        jButtonVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVenta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonVenta.setIconTextGap(10);
        jButtonVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVentaActionPerformed(evt);
            }
        });

        jButtonCompra.setBackground(new java.awt.Color(0, 0, 0));
        jButtonCompra.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jButtonCompra.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zIMG/carrito.png"))); // NOI18N
        jButtonCompra.setText("Compras");
        jButtonCompra.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        jButtonCompra.setBorderPainted(false);
        jButtonCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCompra.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonCompra.setIconTextGap(10);
        jButtonCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCompraActionPerformed(evt);
            }
        });

        jButtonSelectCV.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jButtonSelectCV.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSelectCV.setText("Comprar");
        jButtonSelectCV.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        jButtonSelectCV.setBorderPainted(false);
        jButtonSelectCV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSelectCV.setIconTextGap(10);
        jButtonSelectCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectCVActionPerformed(evt);
            }
        });

        jComboBoxSelectPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSelectPCActionPerformed(evt);
            }
        });

        jDateChooser1.setForeground(new java.awt.Color(255, 255, 255));
        jDateChooser1.setToolTipText("");
        jDateChooser1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N

        jLabelProvClient.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabelProvClient.setText("Proveedor:");

        jLabelFecha.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabelFecha.setText("Fecha:");

        jLabelErroPvCl.setForeground(new java.awt.Color(255, 0, 51));
        jLabelErroPvCl.setText("*Seleccione uno*");

        jLabelErrorFecha.setForeground(new java.awt.Color(255, 0, 51));
        jLabelErrorFecha.setText("*Seleccione una fecha *");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonVenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jButtonCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelErroPvCl, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelProvClient, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonSelectCV, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelErrorFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxSelectPC, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jButtonCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(jLabelProvClient, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelErroPvCl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxSelectPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelErrorFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jButtonSelectCV, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 716));

        jComboBoxProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProductoActionPerformed(evt);
            }
        });
        add(jComboBoxProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 325, 198, 33));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo de producto", "cantidad", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.setColumnSelectionAllowed(true);
        jTable.getTableHeader().setReorderingAllowed(false);
        jTable.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTablePropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);
        jTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 6, 692, 262));

        jTextFieldPrecio.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTextFieldPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioActionPerformed(evt);
            }
        });
        add(jTextFieldPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 108, -1));

        jLabelErrorPrecio.setForeground(new java.awt.Color(255, 0, 51));
        jLabelErrorPrecio.setText("*Ingrese solo números *");
        add(jLabelErrorPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 402, 199, -1));

        jLabelprecio.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabelprecio.setText("Precio:");
        add(jLabelprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 364, 268, -1));

        jButtonQR.setBackground(new java.awt.Color(0, 0, 0));
        jButtonQR.setForeground(new java.awt.Color(0, 0, 0));
        jButtonQR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zIMG/QR.png"))); // NOI18N
        jButtonQR.setBorder(null);
        jButtonQR.setBorderPainted(false);
        jButtonQR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jButtonQR, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 570, 86, 82));

        jSpinnerInv.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        add(jSpinnerInv, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 527, 105, 36));

        jLabelTotal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelTotal.setText("Total: $0");
        add(jLabelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(866, 283, 130, 39));

        jLabel$.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel$.setText("$");
        add(jLabel$, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 14, 30));
        add(jLabelQr, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 370, 200, 180));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddCVActionPerformed

    private void jButtonVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVentaActionPerformed

    private void jButtonCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCompraActionPerformed

    }//GEN-LAST:event_jButtonCompraActionPerformed

    private void jButtonSelectCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectCVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSelectCVActionPerformed

    private void jComboBoxProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxProductoActionPerformed

    private void jTablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTablePropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_jTablePropertyChange

    private void jComboBoxSelectPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSelectPCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSelectPCActionPerformed

    private void jTextFieldPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAddCV;
    public javax.swing.JButton jButtonCompra;
    public javax.swing.JButton jButtonQR;
    public javax.swing.JButton jButtonSelectCV;
    public javax.swing.JButton jButtonVenta;
    public javax.swing.JComboBox<String> jComboBoxProducto;
    public javax.swing.JComboBox<String> jComboBoxSelectPC;
    public com.toedter.calendar.JDateChooser jDateChooser1;
    public javax.swing.JLabel jLabel$;
    public javax.swing.JLabel jLabelCant;
    public javax.swing.JLabel jLabelErroPvCl;
    public javax.swing.JLabel jLabelErrorCant;
    public javax.swing.JLabel jLabelErrorFecha;
    public javax.swing.JLabel jLabelErrorPrecio;
    public javax.swing.JLabel jLabelFecha;
    public javax.swing.JLabel jLabelProd;
    public javax.swing.JLabel jLabelProvClient;
    public javax.swing.JLabel jLabelQr;
    public javax.swing.JLabel jLabelTotal;
    public javax.swing.JLabel jLabelprecio;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JSpinner jSpinnerInv;
    public javax.swing.JTable jTable;
    public javax.swing.JTextField jTextFieldPrecio;
    // End of variables declaration//GEN-END:variables
}

